User-stats `/user/{id}` enpoint
tdameros/42-transcendence pull request #102
Opened 2024-01-27 02:49 UTC by hferraud

Add `/user/{id}` endpoint that will provide basic statistics about the user.

2024-01-27 10:04 UTC, V-Fries requested changes

2024-01-27 10:04 UTC, V-Fries commented on user_stats/docker/docker-compose.yaml
> +                 gunicorn --chdir src/ user_stats.wsgi:application -w 4 -b 0.0.0.0:8000"
Replace with:
```
        command: sh -c "cp -r /app/user_stats /app/src &&
                        cp -r /app/common /app/src/common &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn --chdir src/ user_stats.wsgi:application -w 4 -b 0.0.0.0:8000"
```

2024-01-27 11:30 UTC, tdameros approved these changes

2024-01-27 12:39 UTC, hferraud commented on user_stats/docker/docker-compose.yaml
> +                 gunicorn --chdir src/ user_stats.wsgi:application -w 4 -b 0.0.0.0:8000"
acdbcbc

2024-01-27 12:40 UTC, EthanDelage approved these changes

2024-01-28 00:25 UTC, V-Fries approved these changes

2024-01-28 12:28 UTC, merged