302 generate random key for access jwt
tdameros/42-transcendence pull request #323
Opened 2024-02-28 14:32 UTC by aLeuleu

2024-02-28 20:07 UTC, tdameros requested changes

2024-02-28 20:07 UTC, tdameros commented on user_management/src/user_management/settings.py
> +print(os.path.join(BASE_DIR, '.env'))
You can delete this print

2024-02-29 06:49 UTC, V-Fries approved these changes

2024-02-29 14:20 UTC, hferraud approved these changes

2024-03-01 12:05 UTC, tdameros approved these changes

2024-03-01 15:39 UTC, merged